import { Monster, MoveInstance, LogEntry, ItemType, ExtrasInventory, GymStatus, JourneyState } from './types';
import { getToken } from './auth';

// Where the backend lives. When the API runs on its own host (Render), set NEXT_PUBLIC_API_URL in the
// Vercel project's Environment Variables to e.g. https://poshow.onrender.com (no trailing slash) and
// REDEPLOY — NEXT_PUBLIC_ values are baked in at build time. Empty = same-origin /api (everything on Vercel).
export const API_BASE = (process.env.NEXT_PUBLIC_API_URL || '').replace(/\/+$/, '');

/** trainer avatar sprite (pixel art generated by the API) */
export function avatarUrl(id: string | null | undefined, scale = 6): string {
  return `${API_BASE}/api/avatars/${id || 'ember'}.png?scale=${scale}`;
}

export class ApiError extends Error {
  constructor(message: string, public status?: number) {
    super(message);
    this.name = 'ApiError';
  }
}

// free hosting sleeps when idle and the first request after that can take ~50s — so the default is
// generous, and the health check below is even more patient
const DEFAULT_TIMEOUT_MS = 30000;

async function request<T>(path: string, init?: RequestInit, timeoutMs = DEFAULT_TIMEOUT_MS): Promise<T> {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), timeoutMs);

  const token = getToken();
  let res: Response;
  try {
    res = await fetch(`${API_BASE}${path}`, {
      ...init,
      signal: controller.signal,
      headers: {
        'Content-Type': 'application/json',
        ...(token ? { Authorization: `Bearer ${token}` } : {}),
        ...(init?.headers ?? {}),
      },
    });
  } catch (err) {
    if (err instanceof DOMException && err.name === 'AbortError') {
      throw new ApiError('Request timed out — the server took too long to respond.');
    }
    throw new ApiError(err instanceof Error ? err.message : 'Network request failed.');
  } finally {
    clearTimeout(timeout);
  }

  if (!res.ok) {
    let detail = res.statusText;
    try {
      const body = await res.json();
      detail = body.detail ?? detail;
    } catch {
      // response wasn't JSON — keep statusText
    }
    throw new ApiError(detail, res.status);
  }
  return res.json() as Promise<T>;
}

// server response shapes (mirrors api/index.py) ⚙
export interface ServerMove {
  id: string;
  name: string;
  type: string;
  power: number;
  accuracy: number;
  pp: number;
  max_pp: number;
}

export interface ServerPokemon {
  id: string;
  species_name: string;
  nickname: string;
  level: number;
  current_hp: number;
  max_hp: number;
  experience: number;
  xp_to_next: number;
  types: string[];
  moves: ServerMove[];
  is_shiny: boolean;
  is_fainted: boolean;
  pokedex_id: number | null;
  ability?: string | null;
  ability_desc?: string | null;
  is_boss?: boolean;
  gym_floor?: number;
}

export interface StartBattleResponse {
  battle_id: string;
  player_pokemon: ServerPokemon;
  wild_pokemon: ServerPokemon;
  log: string[];
}

export interface ScoutResponse {
  candidates: ServerPokemon[];
}

export interface BattleMoveResponse {
  log: string[];
  is_finished: boolean;
  winner: 'player' | 'wild' | null;
  player_pokemon: ServerPokemon;
  wild_pokemon: ServerPokemon;
  xp_gained?: number;
  coins_gained?: number;
  /** present on a win */
  team?: ServerPokemon[];
  inventory?: Record<string, number>;
  pokeballs?: Record<string, number>;
  exp_all?: { used: boolean; per_pokemon: number; pokemon_count: number; level_ups: string[] };
  boss?: { defeated: boolean; flawless: boolean; items: [string, number][] };
  /** story trainer: either {advanced...} (next Pokémon sent out), a win summary, or a loss summary */
  story?: {
    advanced?: boolean;
    name?: string;
    idx?: number;
    size?: number;
    won?: boolean;
    coins?: number;
    badge?: string | null;
    win?: string;
    complete?: boolean;
    unlocked_region?: string | null;
    items?: Record<string, number>;
    blackout?: boolean;
    remaining?: number;
    location?: string;
  };
  gym?: {
    // win
    floor_cleared?: number;
    bp?: number;
    coins?: number;
    badge?: string | null;
    next_floor?: number;
    best?: number;
    total_bp?: number;
    // loss
    run_over: boolean;
    remaining?: number;
    floors_cleared?: number;
  };
}

export interface GymEnterResponse extends StartBattleResponse {
  gym: { floor: number; leader: boolean; trainer: string; theme: string; gym: string | null; level: number };
}

export interface RouteInfo {
  id: string;
  name: string;
  min_level: number;
  max_level: number;
  pokemon: string[];
  rare_rate: number;
}

export interface BossInfo {
  species: string;
  name: string;
  level: number;
  moves: string[];
  ability: string | null;
  nature: string;
  xp_reward: number;
  coin_reward: number;
  claimed_today: boolean;
}

export interface CandyResponse {
  player_pokemon: ServerPokemon;
  remaining: number;
  old_level: number;
  new_level: number;
}

export interface CatchResponse {
  battle_id: string;
  will_catch: boolean;
  message?: string;
  remaining_balls: number;
  [key: string]: unknown;
}

export interface FleeResponse {
  success: boolean;
  message?: string;
  gym?: { run_over: boolean; floors_cleared?: number; best?: number };
}

export interface RosterResponse {
  user_id: number;
  username: string;
  coins: number;
  level: number;
  team: ServerPokemon[];
  collection_count: number;
  pokeballs: Record<string, number>;
  inventory: Record<string, number>;
  needs_starter?: boolean;
  region?: string;
  avatar?: string | null;
}

export interface SwitchResponse {
  log: string[];
  player_pokemon: ServerPokemon;
  wild_pokemon: ServerPokemon;
}

export interface ItemResponse {
  log: string[];
  player_pokemon: ServerPokemon;
  wild_pokemon: ServerPokemon;
  remaining: number;
}

export interface BuyResponse {
  coins: number;
  pokeballs: Record<string, number>;
  inventory: Record<string, number>;
}

export interface HealResponse {
  player_pokemon: ServerPokemon;
  remaining: number;
}

// endpoints ⤙
export interface HealthStatus {
  reachable: boolean;
  persistent: boolean;
}

export async function checkHealth(): Promise<HealthStatus> {
  try {
    const res = await request<{ ok: boolean; database: boolean }>('/api/health', undefined, 65000);
    return { reachable: !!res.ok, persistent: !!res.database };
  } catch {
    return { reachable: false, persistent: false };
  }
}

// ── accounts ──
export interface AuthPayload {
  token: string;
  user_id: number;
  username: string;
  needs_starter: boolean;
}

export function authRegister(username: string, password: string) {
  return request<AuthPayload>('/api/auth/register', { method: 'POST', body: JSON.stringify({ username, password }) });
}

export function authLogin(username: string, password: string) {
  return request<AuthPayload>('/api/auth/login', { method: 'POST', body: JSON.stringify({ username, password }) });
}

export function authMe() {
  return request<{ user_id: number; username: string; needs_starter: boolean }>('/api/auth/me');
}

export function telegramStart() {
  return request<{ code: string; expires_in: number; bot_url: string | null; bot_username: string | null }>(
    '/api/auth/telegram/start',
    { method: 'POST', body: '{}' }
  );
}

export function telegramPoll(code: string) {
  return request<{ status: 'pending' | 'expired' | 'ok' } & Partial<AuthPayload>>('/api/auth/telegram/poll', {
    method: 'POST',
    body: JSON.stringify({ code }),
  });
}

export function chooseStarter(userId: number, region: string, species: string, avatar?: string) {
  return request<RosterResponse>('/api/player/starter', {
    method: 'POST',
    body: JSON.stringify({ user_id: userId, region, species, avatar }),
  });
}

export function getAvatars() {
  return request<{ avatars: { id: string; name: string }[] }>('/api/avatars');
}

// ── journey ──
export function journeyState(userId: number) {
  return request<JourneyState>(`/api/journey/state?user_id=${userId}`);
}

export function journeyTravel(userId: number, to: string) {
  return request<JourneyState>('/api/journey/travel', { method: 'POST', body: JSON.stringify({ user_id: userId, to }) });
}

export function journeyHeal(userId: number) {
  return request<JourneyState & { team: ServerPokemon[] }>('/api/journey/heal', {
    method: 'POST',
    body: JSON.stringify({ user_id: userId }),
  });
}

export interface TrainerStartResponse extends StartBattleResponse {
  story: { trainer: string; name: string; title: string; kind: string; idx: number; size: number; intro: string; badge: string | null };
}

export function journeyTrainerStart(userId: number, username: string, trainerId: string) {
  return request<TrainerStartResponse>('/api/journey/trainer/start', {
    method: 'POST',
    body: JSON.stringify({ user_id: userId, username, trainer_id: trainerId }),
  });
}

export function getRoster(userId: number) {
  return request<RosterResponse>(`/api/player/${userId}/roster`);
}

export function startBattle(
  userId: number,
  username: string,
  target?: { species: string; level: number },
  routeId?: string
) {
  return request<StartBattleResponse>('/api/battle/start', {
    method: 'POST',
    body: JSON.stringify({
      user_id: userId,
      username,
      target_species: target?.species,
      target_level: target?.level,
      route_id: routeId,
    }),
  });
}

export function scoutArea(userId: number, routeId?: string) {
  return request<ScoutResponse>('/api/encounter/scout', {
    method: 'POST',
    body: JSON.stringify({ user_id: userId, route_id: routeId }),
  });
}

export function sendMove(battleId: string, moveName: string, useExpAll = false) {
  return request<BattleMoveResponse>('/api/battle/move', {
    method: 'POST',
    body: JSON.stringify({ battle_id: battleId, move_name: moveName, use_exp_all: useExpAll }),
  });
}

export function gymStatus(userId: number) {
  return request<GymStatus>(`/api/gym/status?user_id=${userId}`);
}

export function gymEnter(userId: number, username: string) {
  return request<GymEnterResponse>('/api/gym/enter', {
    method: 'POST',
    body: JSON.stringify({ user_id: userId, username }),
  });
}

export function gymShopBuy(userId: number, itemId: string, quantity = 1) {
  return request<{ bp: number; inventory: Record<string, number>; pokeballs: Record<string, number> }>(
    '/api/gym/shop/buy',
    { method: 'POST', body: JSON.stringify({ user_id: userId, item_id: itemId, quantity }) }
  );
}

export function getRoutes() {
  return request<{ routes: RouteInfo[] }>('/api/routes');
}

export function getBossToday(userId: number) {
  return request<BossInfo>(`/api/boss/today?user_id=${userId}`);
}

export function startBoss(userId: number, username: string) {
  return request<StartBattleResponse>('/api/boss/start', {
    method: 'POST',
    body: JSON.stringify({ user_id: userId, username }),
  });
}

export function useRareCandy(userId: number, pokemonId: string) {
  return request<CandyResponse>('/api/party/rare-candy', {
    method: 'POST',
    body: JSON.stringify({ user_id: userId, pokemon_id: pokemonId }),
  });
}

export function attemptCatch(battleId: string, ballType: string) {
  return request<CatchResponse>('/api/battle/catch', {
    method: 'POST',
    body: JSON.stringify({ battle_id: battleId, ball_type: ballType }),
  });
}

export function switchPokemon(battleId: string, pokemonId: string) {
  return request<SwitchResponse>('/api/battle/switch', {
    method: 'POST',
    body: JSON.stringify({ battle_id: battleId, pokemon_id: pokemonId }),
  });
}

export function useItem(battleId: string, itemType: string) {
  return request<ItemResponse>('/api/battle/item', {
    method: 'POST',
    body: JSON.stringify({ battle_id: battleId, item_type: itemType }),
  });
}

export function buyItem(userId: number, itemId: string, quantity = 1) {
  return request<BuyResponse>('/api/shop/buy', {
    method: 'POST',
    body: JSON.stringify({ user_id: userId, item_id: itemId, quantity }),
  });
}

export function healParty(userId: number, pokemonId: string, itemType: string) {
  return request<HealResponse>('/api/party/heal', {
    method: 'POST',
    body: JSON.stringify({ user_id: userId, pokemon_id: pokemonId, item_type: itemType }),
  });
}

export function flee(battleId: string) {
  return request<FleeResponse>('/api/battle/flee', {
    method: 'POST',
    body: JSON.stringify({ battle_id: battleId }),
  });
}

// mapping: server pokemon → frontend Monster ദ്ദി(ᵔᗜᵔ)
// hunger/PP/status aren't tracked by the bot yet — honest placeholders, not fabricated data
function spriteUrlFor(pokedexId: number | null): string {
  if (!pokedexId) {
    // No PokeAPI data came back (offline/rate-limited) — a neutral pokeball
    // icon reads better than a broken image, and doesn't imply real data.
    return 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/poke-ball.png';
  }
  return `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/${pokedexId}.gif`;
}

export function mapServerPokemon(sp: ServerPokemon): Monster {
  const moves: MoveInstance[] = sp.moves.map((m) => ({
    id: m.id,
    name: m.name,
    type: m.type,
    power: m.power,
    accuracy: (m.accuracy ?? 100) / 100, // backend sends 0-100, frontend math expects 0-1
    pp: m.pp,
    maxPp: m.max_pp,
  }));

  return {
    uid: sp.id,
    speciesId: sp.species_name,
    name: sp.nickname?.toUpperCase() || sp.species_name.toUpperCase(),
    types: sp.types,
    level: sp.level,
    xp: sp.experience,
    xpToNext: sp.xp_to_next,
    hp: sp.current_hp,
    maxHp: sp.max_hp,
    attack: 0, // not surfaced by the API today — battle math runs server-side
    defense: 0,
    status: 'none', // battle_system.py doesn't apply status effects yet
    hunger: 10,
    maxHunger: 10, // the bot has no hunger system — server monsters always read "full"
    portraitUrl: spriteUrlFor(sp.pokedex_id),
    moves,
    catchRate: 0, // unused for server monsters — /api/battle/catch decides server-side
    ability: sp.ability ?? undefined,
    abilityDesc: sp.ability_desc ?? undefined,
    isBoss: sp.is_boss ?? false,
  };
}

let logIdCounter = 0;
export function serverLogToEntries(lines: string[]): LogEntry[] {
  return lines.map((text) => {
    logIdCounter += 1;
    return { id: `srv-${Date.now()}-${logIdCounter}`, text };
  });
}

export function mapServerExtras(inventory: Record<string, number>): ExtrasInventory {
  return {
    exp_all: inventory.exp_all ?? 0,
    rare_candy: inventory.rare_candy ?? 0,
    battle_points: inventory.battle_points ?? 0,
  };
}

// server splits pokeballs/items into two dicts, frontend wants one flat record ฅ^>⩊<^ ฅ
export function mapServerInventory(
  pokeballs: Record<string, number>,
  inventory: Record<string, number>
): Record<ItemType, number> {
  return {
    pokeball: pokeballs.pokeball ?? 0,
    greatball: pokeballs.greatball ?? 0,
    ultraball: pokeballs.ultraball ?? 0,
    potion: inventory.potion ?? 0,
    superpotion: inventory.superpotion ?? 0,
  };
}
