// Starter choices per region — the server validates against the same list (api/index.py STARTERS).
// Every generation orders them grass / fire / water.

export type StarterType = 'grass' | 'fire' | 'water';

export interface StarterChoice {
  species: string;
  pokedexId: number;
  type: StarterType;
}

export interface RegionDef {
  id: string;
  name: string;
  gen: string;
  blurb: string;
  starters: StarterChoice[];
}

const trio = (g: [string, number], f: [string, number], w: [string, number]): StarterChoice[] => [
  { species: g[0], pokedexId: g[1], type: 'grass' },
  { species: f[0], pokedexId: f[1], type: 'fire' },
  { species: w[0], pokedexId: w[1], type: 'water' },
];

export const REGIONS: RegionDef[] = [
  { id: 'kanto', name: 'Kanto', gen: 'I', blurb: 'Where it all began', starters: trio(['bulbasaur', 1], ['charmander', 4], ['squirtle', 7]) },
  { id: 'johto', name: 'Johto', gen: 'II', blurb: 'Old towns, older legends', starters: trio(['chikorita', 152], ['cyndaquil', 155], ['totodile', 158]) },
  { id: 'hoenn', name: 'Hoenn', gen: 'III', blurb: 'Sea and sky', starters: trio(['treecko', 252], ['torchic', 255], ['mudkip', 258]) },
  { id: 'sinnoh', name: 'Sinnoh', gen: 'IV', blurb: 'Snow and myth', starters: trio(['turtwig', 387], ['chimchar', 390], ['piplup', 393]) },
  { id: 'unova', name: 'Unova', gen: 'V', blurb: 'A big bright city', starters: trio(['snivy', 495], ['tepig', 498], ['oshawott', 501]) },
  { id: 'kalos', name: 'Kalos', gen: 'VI', blurb: 'Style and elegance', starters: trio(['chespin', 650], ['fennekin', 653], ['froakie', 656]) },
  { id: 'alola', name: 'Alola', gen: 'VII', blurb: 'Island trials', starters: trio(['rowlet', 722], ['litten', 725], ['popplio', 728]) },
  { id: 'galar', name: 'Galar', gen: 'VIII', blurb: 'Stadium lights', starters: trio(['grookey', 810], ['scorbunny', 813], ['sobble', 816]) },
  { id: 'paldea', name: 'Paldea', gen: 'IX', blurb: 'Open-world adventure', starters: trio(['sprigatito', 906], ['fuecoco', 909], ['quaxly', 912]) },
];

/** trainer avatars — must match api/_lib/avatars.py (the sprites themselves are generated by the API) */
export const AVATAR_CHOICES: { id: string; name: string }[] = [
  { id: 'ember', name: 'Ember' },
  { id: 'marina', name: 'Marina' },
  { id: 'sprout', name: 'Sprout' },
  { id: 'dusk', name: 'Dusk' },
  { id: 'sunny', name: 'Sunny' },
  { id: 'frost', name: 'Frost' },
];

export function starterSprite(pokedexId: number): string {
  return `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/${pokedexId}.gif`;
}

/** static fallback if a showdown gif doesn't exist for that species */
export function starterStillSprite(pokedexId: number): string {
  return `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${pokedexId}.png`;
}
